### ISSUE TITLE
AttributeError: 'depthai.node.Script' object has no attribute 'setScriptData'

### ISSUE THREAD

**Issue by ycj1124** [geaxgx/depthai_blazepose#33]
I found a program using lazepose:https://github.com/Atzingen/QuickiumGymI 
 I download the requirements as the requirements.yml follows,when I try to run the quickium_solution.py,it happened like this :
Pose detection blob file : /home/ycj/QuickiumGym-main/scores/blazepose/models/pose_detection_sh4.blob
Landmarks using blob file : /home/ycj/QuickiumGym-main/scores/blazepose/models/pose_landmark_full_sh4.blob
Internal camera image size: 576 x 324 - pad_h: 126
Creating pipeline...
Creating Color Camera...
Traceback (most recent call last):
File "quickium_solution.py", line 105, in
pose = BlazeposeDepthai()
File "/home/ycj/QuickiumGym-main/scores/blazepose/BlazeposeDepthaiEdge.py", line 98, in init
self.device = dai.Device(self.create_pipeline())
File "/home/ycj/QuickiumGym-main/scores/blazepose/BlazeposeDepthaiEdge.py", line 143, in create_pipeline
manager_script.setScriptData(self.build_manager_script())
AttributeError: 'depthai.node.Script' object has no attribute 'setScriptData'
![2022-10-08 20-13-36 的屏幕截图](https://user-images.githubusercontent.com/55937464/194753997-5161a74d-4cea-4468-89c8-db417865877b.png)
what could be the problem? should I replace the whole "blazepose" folder in that program  with yours ?thank you very much!

**Comment by geaxgx** [comment]
setScriptData() was used in an older version of the depthai library. It is obsolete now. You can try with setScript() instead. Or you can try as you suggested, to replace the blazepose folder by mine (I can't say for sure that it will work as I don't know how it is used in the repo QuickiumGymI).
