### ISSUE TITLE
RuntimeError: No available devices 

### ISSUE THREAD

**Issue by FlavioLorenzi** [geaxgx/depthai_blazepose#35]
Hi, i'm trying to run and test your repository, but every time I launch this **python3 demo.py -i path/to/video.mp4** , I get the following error:

Pose detection blob file : depthai_blazepose/models/pose_detection_sh4.blob
Landmarks using blob file : depthai_blazepose/models/pose_landmark_full_sh4.blob
Video FPS: 30
Original frame size: 852x480
Padding on height : 186
Frame working size: 852x480
2254 anchors have been created
Creating pipeline...
Creating Pose Detection Neural Network...
Creating Landmark Neural Network...
Pipeline created.
Traceback (most recent call last):
  File "demo.py", line 46, in <module>
    pose = BlazeposeDepthai(input_src=args.input, 
  File "depthai_blazepose/BlazeposeDepthai.py", line 175, in __init__
    self.device = dai.Device(self.create_pipeline())
RuntimeError: No available devices

Can you explain me why this error appear?
Thank you,
Bests

**Comment by geaxgx** [comment]
Which OAK device are you using ?

**Comment by tristanle22** [comment]
Does it only with when an OAK device is connected?

**Comment by geaxgx** [comment]
@tristanle22 This repo works only with an OAK device connected.

**Comment by tristanle22** [comment]
I see, thks!

**Comment by grpinto** [comment]
I have the same problem, how can I solve this, where can i get the OAK device ?

**Comment by tristanle22** [comment]
you'd have to buy an OAK device. Luxonis is the manufacturer: https://www.luxonis.com/
