### ISSUE TITLE
"No available devices" on Windows

### ISSUE THREAD

**Issue by gb2111** [geaxgx/depthai_blazepose#4]
I was trying to run BlazeposeDepthai.py either with webcam or filename on Window but each time I get error.
Can you help?

```896 anchors have been created
Creating pipeline...
Creating Pose Detection Neural Network...
Creating Landmark Neural Network...
Pipeline created.
Traceback (most recent call last):
  File "D:/Users/Downloads/depthai_blazepose-main/depthai_blazepose-main/BlazeposeDepthai.py", line 604, in <module>
    ht.run()
  File "D:/Users/Downloads/depthai_blazepose-main/depthai_blazepose-main/BlazeposeDepthai.py", line 408, in run
    device = dai.Device(self.create_pipeline())
RuntimeError: No available devices```

**Comment by geaxgx** [comment]
RuntimeError: No available devices : it is the message you get when no OAK* device is connected on your usb port.
What device are you using ? Have you checked the connection ?

**Comment by geaxgx** [comment]
No more activity on this thread. Closing.
