### ISSUE TITLE
'Couldn't read data from stream: 'manager_out' (X_LINK_ERROR)' on OAK-D S2, M1 Mac

### ISSUE THREAD

**Issue by mngyuan** [geaxgx/depthai_blazepose#42]
Getting the following error on my M1 Mac with the OAK-D S2 camera:

```
(venv) ~/Luxonis/depthai_blazepose ⎇ (main)
✗ ➜  python3 demo.py -e
Pose detection blob file : /Users/liuyue/Luxonis/depthai_blazepose/models/pose_detection_sh4.blob
Landmarks using blob file : /Users/liuyue/Luxonis/depthai_blazepose/models/pose_landmark_full_sh4.blob
Internal camera FPS set to: 20
Internal camera image size: 1152 x 648 - pad_h: 252
Creating pipeline...
Creating Color Camera...
Creating Pose Detection pre processing image manip...
Creating Pose Detection Neural Network...
Creating Pose Detection post processing Neural Network...
Creating Landmark pre processing image manip...
Creating DiveideBy255 Neural Network...
Creating Landmark Neural Network...
Pipeline created.
[19443010C1351C1300] [1.1.4] [1.199] [NeuralNetwork(5)] [warning] Network compiled for 1 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[19443010C1351C1300] [1.1.4] [1.200] [NeuralNetwork(9)] [warning] Network compiled for 4 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[19443010C1351C1300] [1.1.4] [1.433] [NeuralNetwork(4)] [warning] Network compiled for 4 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[19443010C1351C1300] [1.1.4] [1.446] [NeuralNetwork(5)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
Pipeline started - USB speed: SUPER
[19443010C1351C1300] [1.1.4] [1.446] [NeuralNetwork(9)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
[19443010C1351C1300] [1.1.4] [1.446] [NeuralNetwork(4)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
[19443010C1351C1300] [1.1.4] [7.415] [system] [critical] Fatal error. Please report to developers. Log: 'ResourceLocker' '358'
libc++abi: terminating due to uncaught exception of type std::runtime_error: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'manager_out' (X_LINK_ERROR)'
Stack trace (most recent call last):
#10   Object "libc++.1.dylib", at 0x180d313ef, in std::rethrow_exception(std::exception_ptr) + 23
#9    Object "libc++abi.dylib", at 0x180dbfeeb, in std::terminate() + 55
#8    Object "libc++abi.dylib", at 0x180dbff47, in std::__terminate(void (*)()) + 15
#7    Object "libobjc.A.dylib", at 0x180a8703b, in _objc_terminate() + 159
#6    Object "libc++abi.dylib", at 0x180db03b3, in demangling_terminate_handler() + 319
#5    Object "libc++abi.dylib", at 0x180dc0b83, in abort_message + 131
#4    Object "libsystem_c.dylib", at 0x180d15ae7, in abort + 179
#3    Object "libsystem_pthread.dylib", at 0x180e07c27, in pthread_kill + 287
#2    Object "libsystem_platform.dylib", at 0x180e36a83, in _sigtramp + 55
#1    Object "depthai.cpython-310-darwin.so", at 0x289cff467, in backward::SignalHandling::sig_handler(int, __siginfo*, void*) + 19
#0    Object "depthai.cpython-310-darwin.so", at 0x289cff4bf, in backward::SignalHandling::sig_handler(int, __siginfo*, void*) + 107
[1]    75155 abort      python3 demo.py -e

```

Does this repository support Apple Silicon macs?

**Comment by ynkynkynk** [comment]
I am getting the same error in the same environment.
[crash_dump.json](https://github.com/user-attachments/files/17033152/crash_dump.json)

**Comment by regorwislon** [comment]
I get a related (?) error as below when trying to run the demo.py script in edge mode (ie with -e) on both a win11 and Raspberry Pi 5 (Bookworm) platform and just cannot get it to run.  It sometimes runs for a few frames before crashing. The demo runs fine in host mode. I have attached the win11 platform crash dump log. Any help in resolving this would be appreciated
[crash_dump.json](https://github.com/user-attachments/files/18403640/crash_dump.json)
.

Pose detection blob file : C:\Users\***\PycharmProject\BlazePose\models\pose_detection_sh4.blob
Landmarks using blob file : C:\Users\***\PycharmProject\BlazePose\models\pose_landmark_full_sh4.blob
Internal camera FPS set to: 20
Internal camera image size: 1152 x 648 - pad_h: 252
Creating pipeline...
Creating Color Camera...
Creating Pose Detection pre processing image manip...
Creating Pose Detection Neural Network...
Creating Pose Detection post processing Neural Network...
Creating Landmark pre processing image manip...
Creating DiveideBy255 Neural Network...
Creating Landmark Neural Network...
Pipeline created.
[18443010F107C80F00] [1.2.2.2] [1.007] [NeuralNetwork(4)] [warning] Network compiled for 4 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[18443010F107C80F00] [1.2.2.2] [1.240] [NeuralNetwork(9)] [warning] Network compiled for 4 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[18443010F107C80F00] [1.2.2.2] [1.241] [NeuralNetwork(5)] [warning] Network compiled for 1 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[18443010F107C80F00] [1.2.2.2] [1.253] [NeuralNetwork(4)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
Pipeline started - USB speed: SUPER
[18443010F107C80F00] [1.2.2.2] [1.253] [NeuralNetwork(9)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
[18443010F107C80F00] [1.2.2.2] [1.254] [NeuralNetwork(5)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
Traceback (most recent call last):
  File "C:\Users\***\PycharmProject\BlazePose\demo.py", line 12, in <module>
    frame, body = tracker.next_frame()
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\PycharmProject\Blazepose\BlazeposeDepthaiEdge.py", line 486, in next_frame
    res = marshal.loads(self.q_manager_out.get().getData())
                        ^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'manager_out' (X_LINK_ERROR)'
[2025-01-14 13:03:20.909] [depthai] [error] Device with id 18443010F107C80F00 has crashed. Crash dump logs are stored in: C:\Users\***\PycharmProject\BlazePose\.cache\depthai\crashdumps\3219dfc047e77aa055f32b83fa138c1f9304a067\crash_dump.json - please report to developers.

Process finished with exit code 1

**Comment by yaoxichen** [comment]
I'm having the same problem with edge-side deployments.
